name: uniform-relations
version: 0.0.1.3.2
# cabal-version: >=1.22
# build-type: Simple
license: GPL
license-file: GPL_3
maintainer: Andrew U. Frank <andrewufrank@gmail.com>
author: Andrew Frank
category: 'Geometry, Uniform, Relations'
synopsis: uniform wrapper to handle relations and a naive triple store
description: |
  a base functions to store data in a naive triple store 
  which is simplified, non optimized and strongly typed.
  Functions to handle relations given as list of pairs.

# source-repository head
#     type: git
#     location: https://github.com/andrewufrank/uniform-http.git

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- HTF
- uniformBase >=0.1.4.2
- extra
#- uniform-geometry >=0.0.1.7
# - gloss
- monads-tf
# - aop-prelude
# - containers

# # - vector-space
# - linear
# - lens
# - qhull ==0.1.0.3
# - vector-algorithms # not needed for lts 18.28 ==0.8.0.3 # -- to force qhull
# - insert-ordered-containers
# - pretty-show 

# # for hgeometry
# - hgeometry 
# - hgeometry-combinatorial
# # - linear
# - data-clist
# # - aeson-pretty
# - vector 
# - array                    >= 0.5
#  - lens
# - semigroups
# - vector-circular


library:
  source-dirs: 
  - src 
 

executables: 
  exec: 
    main:   Main.hs
    source-dirs:  app
    dependencies: 
    - uniform-relations
    # - uniform-geometry

tests:
  test1:
    main:                Testing.hs
    source-dirs:         tests
    dependencies:
    - uniformBase
    - uniform-relations
    # - uniform-geometry
    - HTF
    - quickcheck-text
    # - uniform-strings
    # - uniform-http
    # - uniform-watch

