name: uniform-relations
version: 0.0.1.3.2
# cabal-version: >=1.22
# build-type: Simple
license: GPL
license-file: GPL_3
maintainer: Andrew U. Frank <andrewufrank@gmail.com>
author: Andrew Frank
category: 'Geometry, Uniform, Relations'
synopsis: uniform wrapper to handle relations and a naive triple store
description: |
  a base functions to store data in a naive triple store 
  which is simplified, non optimized and strongly typed.
  Functions to handle relations given as list of pairs.

# source-repository head
#     type: git
#     location: https://github.com/andrewufrank/uniform-http.git

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- HTF
- uniformBase >=0.1.4.2
- extra
- lens
- monads-tf
 


library:
  source-dirs: 
  - src 
 

executables: 
  exec: 
    main:   Main.hs
    source-dirs:  app
    dependencies: 
    - uniform-relations
    # - uniform-geometry

tests:
  test1:
    main:                Testing.hs
    source-dirs:         tests
    dependencies:
    - uniformBase
    - uniform-relations
    # - uniform-geometry
    - HTF
    - quickcheck-text
    # - uniform-strings
    # - uniform-http
    # - uniform-watch

