name: uniform-field
version: 0.0.1.1
# cabal-version: >=3.6 would go to verbatim, but usually not required
# build-type: Simple
license: GPL
license-file: GPL_3
maintainer: Andrew U. Frank <andrewufrank@gmail.com>
author: Andrew Frank
category: 'Geometry, Uniform, GIS'
synopsis: uniform wrapper for functions producing the field data in a GIS
description: |
  - two modules wtih code to computer 2dimensional Fourier transformation and their inverse: 
    - FourierTextBook - an extremely non-optimized code close to a text book
    - FourierComfort - using comfort-array to access the FFTW (Fastest Fourier Transform in the West)
  - functions to construct the field as a function pnt2d -> value


# source-repository head
#     type: git
#     location: https://github.com/andrewufrank/u2giscore.git/uniform-field

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- HTF
- uniformBase >=0.1.4.2
- uniform-geometry >= 0.0.1.8
- extra
# - containers
- repa-fftw
- repa
# - repa-array
- comfort-array
- comfort-fftw
- vector 

library:
  source-dirs: 
  - src
 

executables: 
  exec: 
    main:   Main.hs
    source-dirs:  app
    dependencies: 
    - uniform-field

tests:
  test:
    main:                Testing.hs
    source-dirs:         tests
    dependencies:
    - uniform-field
    - HTF
    - quickcheck-text
    - uniformBase
    # - uniform-strings
    # - uniform-http
    # - uniform-watch


