name: uniform-readshow
version: 0.0.1.0

build-type: Simple
license: GPL
license-file: GPL_3
maintainer: Andrew U. Frank <andrewufrank@gmail.com>
author: Andrew Frank
copyright:    2021 Andrew U. Frank
category: Uniform
synopsis: a uniform set of instances for read and show 
description: | 
    There are a few data types for which `read . show = id` 
    is not achieved: UTC, Path. 
    There are also cases, where the added quotation marks are problematic because the content shown contains quotation marks (e.g. JSON)


# source-repository: head
#     type: git
#     location: https://github.com/andrewufrank/uniform-example.git

extra-source-files:
    - README.md
    - ChangeLog.md

dependencies:
    - base  
    - uniformBase
    - text # remove if not used later
    # - monads-tf
    # - exceptions
    # - safe
    # - uniform-strings
    # - HTF
    # - uniform-algebras
    # - uniform-strings
    # - uniform-error 

library:
    source-dirs: src

executables:
  example-exe:
    main:                readShowMain.hs
    source-dirs:         app
#

tests: 
    tests_example:
        main: Testing.hs
        source-dirs: tests
        # type:       exitcode-stdio-1.0
        dependencies:  
            - uniformBase
            - HTF
            - uniform-readshow
            # - test-invariant
            # - quickcheck-text
            # - uniform-convenience
        buildable: True
