name: uniform-geometry
version: 0.0.1.7
# cabal-version: >=1.22
# build-type: Simple
license: GPL
license-file: GPL_3
maintainer: Andrew U. Frank <andrewufrank@gmail.com>
author: Andrew Frank
category: 'Geometry, Uniform'
synopsis: uniform wrapper for geometry functions
description: |
  - some basic data types for 2d points (represented as Double) and 
  - functions (for ccw test, incenter and circumcenter)
  - delaunay (and voronoi) through access to qhull (suspended) and hgeometry
  - graphical geometry output (through gloss)  

# source-repository head
#     type: git
#     location: https://github.com/andrewufrank/uniform-http.git

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- HTF
- uniformBase >=0.1.4.1

- extra
- containers

# - vector-space
- linear
- lens
# - qhull ==0.1.0.4
# - vector-algorithms # not needed for lts 18.28 ==0.8.0.3 # -- to force qhull
# - insert-ordered-containers
# - pretcabal ty-show 

# for hgeometry
- hgeometry >= 0.14 && < 0.15
- hgeometry-combinatorial >= 0.14 && < 0.15
# - linear
- data-clist
# - aeson-pretty
- vector 
# - array                    >= 0.5
#  - lens
# - semigroups
- vector-circular
- gloss


library:
  source-dirs: 
  - src
 

executables: 
  exec: 
    main:   Main.hs
    source-dirs:  app
    dependencies: 
    - uniform-geometry

tests:
  test1:
    main:                Testing.hs
    source-dirs:         tests
    dependencies:
    - uniform-geometry
    - HTF
    - quickcheck-text
    # - uniform-strings
    # - uniform-http
    - uniformBase
    # - uniform-watch


#     exposed-modules:
#             Uniform.Http
#             -- the next two must not be imported
#             -- except for testing here
#              Uniform.HttpCall
#              Uniform.HttpURI
#     exposed: True
#     buildable: True
#     default-language: Haskell2010
#     hs-source-dirs: .
#     other-modules:

# Test-Suite httpTestAuto
#     type:       exitcode-stdio-1.0
#     main-is:    Testing.hs
#     build-depends: base, HTF
#         -- , uniform-fileio
#         , uniform-strings
#         , uniform-error
#         , uniform-http
#         , uniform-json
#         -- , aeson
# --        -- needed because the two files

#             , uniform-algebras
#             , network-uri
# -- for tests
#             , HTF
#             , test-invariant
#     default-language: Haskell2010
#     hs-source-dirs: tests
#     other-modules:
#                  Uniform.HttpCall_test
#                  Uniform.HttpURI_test
# --             Uniform.HttpCall
# --             Uniform.HttpURI
