name:         uniform-convenience
version:      0.0.9.7
license:      GPL
license-file: GPL_3
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category: Uniform
synopsis: convenience functions
description: some convenience functions, which are not good algebras
    and debatable
    exports in multiple modules
    0.0.9.6 for cabal 8.10.4 may 2021
    0.0.9.7 for   uniformBase-0.1.1

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
# - monads-tf
# - safe
# - text
- csv
- iso639
- uniformBase  
- uniform-json   
- HTF # for the construction of TestHarness.hs

library:
  source-dirs: src

# this is only a library, no directly executable
# executables:
#   primo-exe:
#     main:                Testing.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - uniform-algebras

tests:
  convenience-test:
    main:                Testing.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - uniformBase
    - HTF
    - test-invariant
    - quickcheck-text
    - uniform-convenience
    

