name: uniform-hqSchema
version: 0.0.1.2
# cabal-version: >=1.22
# build-type: Simple
license: GPL
license-file: GPL_3
maintainer: Andrew U. Frank <andrewufrank@gmail.com>
author: Andrew Frank
category: 'Geometry, Uniform, Relations'
synopsis: the schema (i.e. data types) necessary to load geometry to a naive triple store (using the half-quad representation)
description: |
  converting the extracted relations from a triangulation and reformat it for storage into a triple store

# source-repository head
#     type: git
#     location: https://github.com/andrewufrank/uniform-http.git

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- HTF
- uniformBase >=0.1.4.2
- extra
- uniform-geometry >=0.0.1.7.1
- uniform-relations >=0.0.1.3
- uniform-graphics 

# - uniform-hqSchema
# - gloss
- monads-tf
- transformers
# - aop-prelude
# - containers

# # - vector-space
# - linear
# - lens
# - qhull ==0.1.0.3
# - vector-algorithms # not needed for lts 18.28 ==0.8.0.3 # -- to force qhull
# - insert-ordered-containers
# - pretty-show 

# # for hgeometry
# - hgeometry 
# - hgeometry-combinatorial
# # - linear
# - data-clist
# # - aeson-pretty
# - vector 
# - array                    >= 0.5
#  - lens
# - semigroups
# - vector-circular


library:
  source-dirs: 
  - src 
 

executables: 
  exec:    # necessary to introduce a name (because tests is a second option)
    main:   Main.hs
    source-dirs:  app
    dependencies: 
    - uniform-hqSchema
    # - uniform-geometry

tests:
  test:
    main:                Testing.hs
    source-dirs:         tests
    dependencies:
    - uniformBase
    # - uniform-relations
    # - uniform-geometry
    - uniform-hqSchema

    - HTF
    - quickcheck-text
    # - uniform-strings
    # - uniform-http
    # - uniform-watch
    # - uniform-geometry

#     exposed-modules:
#             Uniform.Http
#             -- the next two must not be imported
#             -- except for testing here
#              Uniform.HttpCall
#              Uniform.HttpURI
#     exposed: True
#     buildable: True
#     default-language: Haskell2010
#     hs-source-dirs: .
#     other-modules:

# Test-Suite httpTestAuto
#     type:       exitcode-stdio-1.0
#     main-is:    Testing.hs
#     build-depends: base, HTF
#         -- , uniform-fileio
#         , uniform-strings
#         , uniform-error
#         , uniform-http
#         , uniform-json
#         -- , aeson
# --        -- needed because the two files

#             , uniform-algebras
#             , network-uri
# -- for tests
#             , HTF
#             , test-invariant
#     default-language: Haskell2010
#     hs-source-dirs: tests
#     other-modules:
#                  Uniform.HttpCall_test
#                  Uniform.HttpURI_test
# --             Uniform.HttpCall
# --             Uniform.HttpURI
