name: uniform-hqSchema
version: 0.0.1.4
# cabal-version: >=1.22
# build-type: Simple
license: GPL
license-file: GPL_3
maintainer: Andrew U. Frank <andrewufrank@gmail.com>
author: Andrew Frank
category: 'Geometry, Uniform, Relations'
synopsis: the schema (i.e. data types) necessary to load geometry to a naive triple store (using the half-quad representation)
description: |
  converting the extracted relations from a triangulation and reformat it for storage into a triple store
tested-with: ghc == 9.0.2
# source-repository head
#     type: git
#     location: https://github.com/andrewufrank/uniform-http.git

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- HTF
- uniformBase >=0.1.4.2
- extra
- uniform-geometry >=0.0.1.8
- uniform-relations >=0.0.1.3.2
- uniform-graphics >=0.0.1.2

# - uniform-hqSchema
# - gloss
- monads-tf 


library:
  source-dirs: 
  - src 
 

executables: 
  exec:    # necessary to introduce a name (because tests is a second option)
    main:   Main.hs
    source-dirs:  app
    dependencies: 
    - uniform-hqSchema
    # - uniform-geometry

tests:
  test:
    main:                Testing.hs
    source-dirs:         tests
    dependencies:
    - uniformBase
    # - uniform-relations
    # - uniform-geometry
    - uniform-hqSchema

    - HTF
    - quickcheck-text

