name:         uniform-cmdLineArgs
version:      0.0.1.0
license:      GPL
license-file: GPL_3
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category:     CmdLineArgs
synopsis:     a convenient handling of command line arguments
description: | 
  deals with the command line arguments and fills with decent defaults


extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- monads-tf
- uniformBase >=0.1.3
- HTF
- optparse-applicative
# # - test-invariant

library:
  source-dirs: src

# this is only a library, no directly executable
# executables:
#   primo-exe:
#     main:                Testing.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - uniform-algebras

# tests:
#   strings-test:
#     main:                Testing.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - uniform-algebras
#     - HTF
#     - test-invariant
#     - quickcheck-text
#     - uniform-strings
#     - uniform-fileio
#     - uniform-cmdLineArgs
