name:         uniform-startapp
version:      0.0.9.7
license:      GPL
license-file: GPL_3
maintainer:   Andrew U. Frank <andrewufrank@gmail.com>
author:       Andrew Frank
copyright:    2021 Andrew U. Frank
category: Uniform
synopsis: starts an app and shows errors at end
description:  useful to start code running in ErrIO
    0.0.9.7 for   uniformBase-0.1.1, split from uniform-convenience

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
# - monads-tf
# - safe
# - text
# - csv
# - iso639
- uniformBase >=0.1.3
# - uniform-fileio
# - uniform-json   
# - HTF # for the construction of TestHarness.hs

library:
  source-dirs: src


# executables:
#   harness-exe:
#     main:                Main.hs
#     source-dirs:         app
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - uniformBase
#     # - uniform-convenience

# tests:
#   convenience-test:
#     main:                Testing.hs
#     source-dirs:         tests
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - uniformBase
#     - HTF
#     - test-invariant
#     - quickcheck-text
#     - uniform-convenience
    

